-- MySQL Script generated by MySQL Workbench
-- Sun Sep 26 15:47:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema schooldb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `schooldb` ;

-- -----------------------------------------------------
-- Schema schooldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `schooldb` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `schooldb` ;

-- -----------------------------------------------------
-- Table `schooldb`.`tb_course_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schooldb`.`tb_course_status` ;

CREATE TABLE IF NOT EXISTS `schooldb`.`tb_course_status` (
  `courseStatusId` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`courseStatusId`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `schooldb`.`tb_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schooldb`.`tb_course` ;

CREATE TABLE IF NOT EXISTS `schooldb`.`tb_course` (
  `courseId` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `courseStatusId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`courseId`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `FK_COURSE_STATUS_idx` (`courseStatusId` ASC) VISIBLE,
  CONSTRAINT `FK_COURSE_STATUS`
    FOREIGN KEY (`courseStatusId`)
    REFERENCES `schooldb`.`tb_course_status` (`courseStatusId`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `schooldb`.`tb_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schooldb`.`tb_person` ;

CREATE TABLE IF NOT EXISTS `schooldb`.`tb_person` (
  `personId` INT NOT NULL AUTO_INCREMENT,
  `nid` INT NULL DEFAULT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`personId`),
  UNIQUE INDEX `nid_UNIQUE` (`nid` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `schooldb`.`tb_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schooldb`.`tb_student` ;

CREATE TABLE IF NOT EXISTS `schooldb`.`tb_student` (
  `studentId` INT NOT NULL AUTO_INCREMENT,
  `personId` INT NULL DEFAULT NULL,
  `classroom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`studentId`),
  INDEX `FK_STUDENT_PERSON_idx` (`personId` ASC) VISIBLE,
  CONSTRAINT `FK_STUDENT_PERSON`
    FOREIGN KEY (`personId`)
    REFERENCES `schooldb`.`tb_person` (`personId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `schooldb`.`tb_teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schooldb`.`tb_teacher` ;

CREATE TABLE IF NOT EXISTS `schooldb`.`tb_teacher` (
  `teacherId` INT NOT NULL AUTO_INCREMENT,
  `personId` INT NULL DEFAULT NULL,
  `subject` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`teacherId`),
  INDEX `FK_TEACHER_PERSON_idx` (`personId` ASC) VISIBLE,
  CONSTRAINT `FK_TEACHER_PERSON`
    FOREIGN KEY (`personId`)
    REFERENCES `schooldb`.`tb_person` (`personId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `schooldb`.`tb_gradebook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schooldb`.`tb_gradebook` ;

CREATE TABLE IF NOT EXISTS `schooldb`.`tb_gradebook` (
  `gradebookId` INT NOT NULL AUTO_INCREMENT,
  `studentId` INT NULL DEFAULT NULL,
  `Q1` DECIMAL(3,2) NOT NULL,
  `Q2` DECIMAL(3,2) NOT NULL,
  `Q3` DECIMAL(3,2) NOT NULL,
  `average` DECIMAL(3,2) NULL DEFAULT NULL,
  `teacherId` INT NULL DEFAULT NULL,
  `courseId` INT NULL DEFAULT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`gradebookId`),
  INDEX `FK_GRADE_STUDENT_idx` (`studentId` ASC) VISIBLE,
  INDEX `FK_GRADE_TEACHER_idx` (`teacherId` ASC) VISIBLE,
  INDEX `FK_GRADE_COURSE_idx` (`courseId` ASC) VISIBLE,
  CONSTRAINT `FK_GRADE_COURSE`
    FOREIGN KEY (`courseId`)
    REFERENCES `schooldb`.`tb_course` (`courseId`),
  CONSTRAINT `FK_GRADE_STUDENT`
    FOREIGN KEY (`studentId`)
    REFERENCES `schooldb`.`tb_student` (`studentId`),
  CONSTRAINT `FK_GRADE_TEACHER`
    FOREIGN KEY (`teacherId`)
    REFERENCES `schooldb`.`tb_teacher` (`teacherId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `schooldb`.`tb_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schooldb`.`tb_rol` ;

CREATE TABLE IF NOT EXISTS `schooldb`.`tb_rol` (
  `rolId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`rolId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `schooldb`.`tb_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schooldb`.`tb_login` ;

CREATE TABLE IF NOT EXISTS `schooldb`.`tb_login` (
  `loginId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `rolId` INT NULL DEFAULT NULL,
  `personId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`loginId`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `FK_LOGIN_ROL_idx` (`rolId` ASC) VISIBLE,
  INDEX `FK_LOGIN_PERSON_idx` (`personId` ASC) VISIBLE,
  CONSTRAINT `FK_LOGIN_PERSON`
    FOREIGN KEY (`personId`)
    REFERENCES `schooldb`.`tb_person` (`personId`),
  CONSTRAINT `FK_LOGIN_ROL`
    FOREIGN KEY (`rolId`)
    REFERENCES `schooldb`.`tb_rol` (`rolId`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
